### ISSUE TITLE
Value for data-counter can not be ~

### ISSUE THREAD

**Issue by datune** [inetis-ch/oc-InputCounter-plugin#2]
Hi, 

just to let you know, using ~ as a value for data-counter in a yaml field, does not work as expected. I had to replace the value with 1, in order to get the input-counter to show up.

**Comment by Fl0Cri** [comment]
Hi,

You're right, I updated the doc.
The idea of using `~` was because it means null in yaml, and I wanted the same behaviour as with the php code to render it as `<input type="..." data-counter>`.
But october doesn't render the data-counter attribute if the value is null.

Just to clarify, actually you can put any value you want for `data-counter` because the js selector that creates the counter only looks for the presence of this attribute. (even `data-counter="false"` would work, that's why I though null could avoid confusion)
